/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Condominio } from "./Condominio";
export type { Lock } from "./Lock";
export * as factories from "./factories";
export { Condominio__factory } from "./factories/Condominio__factory";
export { Lock__factory } from "./factories/Lock__factory";
