/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { Condominio__factory } from "./Condominio__factory";
export { Lock__factory } from "./Lock__factory";
